
steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/devops-casestudy-20200608/mysql-flaskapp/prod:$COMMIT_SHA", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/devops-casestudy-20200608/mysql-flaskapp/prod:$COMMIT_SHA"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=./kubernetes/kustomization.yaml
  - --image=gcr.io/devops-casestudy-20200608/mysql-flaskapp/prod:$COMMIT_SHA
  - --location=us-central1-c
  - --cluster=flask-app-prod
  - --namespace=production
