steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/devops-casestudy-20200608/bib-flaskapp', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/devops-casestudy-20200608/bib-flaskapp']
images: ['gcr.io/devops-casestudy-20200608/bib-flaskapp']