
steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/devops-casestudy-20200608/mysql-flaskapp/prod:$COMMIT_SHA", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/devops-casestudy-20200608/mysql-flaskapp/prod:$COMMIT_SHA"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=./kubernetes/deployment.yaml
  - --image=gcr.io/devops-casestudy-20200608/mysql-flaskapp/prod:$COMMIT_SHA
  - --location=${_CLOUDSDK_COMPUTE_ZONE}
  - --cluster= ${_CLOUDSDK_CONTAINER_CLUSTER}
  - --namespace=${_NAMESPACE}
