apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: flask-app-service
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: flask-app-service
          servicePort: 80
