apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-app
  name: flask-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - image: >-
            gcr.io/devops-casestudy-20200608/github.com/bibek-devops/flask-app-cicd
          imagePullPolicy: Always
          name: falsk-app-image-1
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: flask-app
  name: flask-app-hpa-quir
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-app

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    run: flask-app
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: flask-app